server:
  port: 8080


mybatis:
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: com.example.demo.pojo.*

spring:
  datasource:
    name: louder
    url: jdbc:mysql://121.5.27.43:3306/louder
    username: root
    password: louder123
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.163.com
    username: fitzwang202006@163.com
    password: BTHSVBTDJRABAUOJ
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          ssl:
            enabled: true

  redis:
    jedis:
      pool:
        max-active: 100
        max-wait: 1000
        max-idle: 10
    host: 121.5.27.43
    password: louder123
    port: 6379
    timeout: 5000
  application:
    name: louder_producer

rocketmq:
  name-server: 121.5.27.43:9876
  producer:
    group: my-group
    send-message-timeout: 30000

mail:
  fromMail:
    addr: fitzwang202006@163.com



